name = "theme_jk"
license = "MIT"
licenselink = "https://github.com/zhe/hugo-theme-slim/blob/master/LICENSE.md"
description = "Theme for personal blog, adapted from theme slim and jekyll-tufte"
homepage = ""
tags = ["blog"]
features = ["blog"]
min_version = 0.18
